### ISSUE TITLE
Add endpoint searching when pointed to base URL

### ISSUE THREAD

**Issue by iCarossio** [gsmith257-cyber/GraphCrawler#1]
Hey @gsmith257-cyber this is not really an issue but I saw you wanted to `Add endpoint searching when pointed to base URL`. I really encourage you to use https://github.com/Escape-Technologies/graphinder which we created exactly for this purpose ;) We can help if needed once you plan this feature!

See the blog post too: https://blog.escape.tech/graphinder-lightweight-and-blazing-fast-graphql-endpoint-finder/

**Comment by gsmith257-cyber** [comment]
Thanks for the recommendation. Ill look into it.
