### ISSUE TITLE
Dosen't work on api.site.com/graphql

### ISSUE THREAD

**Issue by gprime31** [gsmith257-cyber/GraphCrawler#2]
Hi,
i tried 3 known with a path similar to https://api.site.com/graphql all with introspection enabeled and it says......
.[+] Downloading schema for https://api.site.com/graphql ...
.[-] Error downloading schema, is introspection enabled?
.[-] Exiting...
.[+] Done

any ideas what's going on?

**Comment by gsmith257-cyber** [comment]
Would you be able to provide more details? Can you pull up the schema in graphiql or a similar tool? Its sending a pretty standard introspection query to grab the schema so it shouldn't be running into an error there.

**Comment by gprime31** [comment]
![2022-07-21_21-10](https://user-images.githubusercontent.com/44535257/180340489-22ccd8a4-9ba4-4f4c-ab50-91f6d1a311ae.png)

**Comment by gprime31** [comment]
command used:
python3 graphCrawler.py -u https://api.redacted.com/graphql -a "Content-Type: application/json"

**Comment by gsmith257-cyber** [comment]
Ill dig into this. Currently doing an exam but once I finish Ill get on it. Thank you for the report.

**Comment by gprime31** [comment]
no problem, looks like a great tool, appreciate your work.

**Comment by gsmith257-cyber** [comment]
Thanks for being so patient. I just submitted the report for the eWPT exam. I got a chance to look over and troubleshoot the issue and I think the last commit should have fixed it. Try again with it now.

**Comment by gprime31** [comment]
Working now, awesome thanks.

**Comment by stephenbond** [comment]
Hi, I am having same problem:

![image](https://user-images.githubusercontent.com/28650420/213726571-6784cfaa-9153-4b7c-832d-0077227390f1.png)

![image](https://user-images.githubusercontent.com/28650420/213726849-4f7f9dd3-3e89-487b-ad6a-b4c172f8b8ff.png)

**Comment by stephenbond** [comment]
![image](https://user-images.githubusercontent.com/28650420/213727004-f7c7263d-e4a7-450b-b10e-bd532ae8afc7.png)

**Comment by gsmith257-cyber** [comment]
> Hi, I am having same problem:
> 
> ![image](https://user-images.githubusercontent.com/28650420/213726571-6784cfaa-9153-4b7c-832d-0077227390f1.png)
> 
> ![image](https://user-images.githubusercontent.com/28650420/213726849-4f7f9dd3-3e89-487b-ad6a-b4c172f8b8ff.png)

Hey stephenbond. Can you try running GraphCrawler without adding the "Content-Type" header? It should already add that header and so might be causing a collision there.

**Comment by stephenbond** [comment]
Hi, i have tried that but it does not help unfortunately.

**Comment by gsmith257-cyber** [comment]
> Hi, i have tried that but it does not help unfortunately.

Interesting... Ill take a deep dive and see what is up with it.

**Comment by gsmith257-cyber** [comment]
> Hi, i have tried that but it does not help unfortunately.

So I am unable to replicate this with multiple different endpoints. Can you check if the user-agent header is required? I am unable to debug what I can't replicate.

**Comment by stephenbond** [comment]
The user-agent is not required.

**Comment by gsmith257-cyber** [comment]
> The user-agent is not required.
> 
> 

Unfortunately, I still am unable to replicate this issue and would need to see how it's being used. My last bit without that is to make sure you have the most up-to-date version by running 'git pull'
