### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ghost** [gsmith257-cyber/GraphCrawler#4]
Tool looks 🔥🔥, 

Can you add docker support.

**Comment by gsmith257-cyber** [comment]
Good idea. I'll add it once I have some freetime.

**Comment by this-is-r-gaurav** [comment]
@gsmith257-cyber Do you accept PR on this?

**Comment by gsmith257-cyber** [comment]
@this-is-r-gaurav if you start an appropriate PR I will accept it.
