### ISSUE TITLE
Docker: Arguments not being passed

### ISSUE THREAD

**Issue by cprichmond** [gsmith257-cyber/GraphCrawler#6]
I had an issue (on mac) passing args to run the dockerfile in that they weren't being picked up by `graphCrawler.py`

Apparently, you need to use the exec form of ENTRYPOINT and not the shell form for args to propagate. 

If I, therefore, change the ENTRYPOINT command from what it is currently to `ENTRYPOINT ["python3", "/app/graphCrawler.py"]` it works as expected.

**Comment by gsmith257-cyber** [comment]
Thank you for informing me of this issue, as well as providing a solution. It is fixed now in the dockerfile.
