### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by Drjacky** [gsmith257-cyber/GraphCrawler#7]
I know in the original repo, graphql-path-enum, for supporting macOS an issue still exists: https://gitlab.com/dee-see/graphql-path-enum/-/issues/3, but, have you supported it in your repo? cause when I run it, I get:
> Do you want to get more paths? (y/n): y
Type of the sensative node: user
[+] Getting possible paths to user
sh: ./support/graphql-path-enum: cannot execute binary file

**Comment by gsmith257-cyber** [comment]
There is currently no MacOS support for the version of GraphQL-path-enum used in GraphCrawler. This will be included in next update that I release, or you are welcome to make a contribution and add the support.
