### ISSUE TITLE
Impossible to Map Introspection Disabled GQL APIs for Specific URLs (Apollo Servers Detected)

### ISSUE THREAD

**Issue by XMVZ** [gsmith257-cyber/GraphCrawler#8]
If anyone could give me a hand -- running into this issue with pretty much every GraphQL enumeration / mapping tool or library for the following URLs. I'm not sure if there is some additional variable I'm missing that I need to be including or potentially a different URL? No clue. 

> https://api.hypedrop.com/graphql
[Apollo | Introspection Disabled]

> https://api.hypeup.com/graphql
[Apollo | Introspection Disabled]

> http://api.csgoroll.com/graphql
[Apollo | Introspection Disabled]

Seriously any and all help appreciated as this has been driving me insane! 

Thank you so much for an amazing repo & tool. I hope to be able to utilize it!

x

**Comment by gsmith257-cyber** [comment]
Thanks for using GraphCrawler. Unfortunately we cannot test any endpoints unauthorized and will not be able to support you with this. If introspection is enabled and they can't be mapped then they may be configured correctly and so cannot be tested in this manner.

**Comment by XMVZ** [comment]
> Thanks for using GraphCrawler. Unfortunately we cannot test any endpoints unauthorized and will not be able to support you with this. If introspection is enabled and they can't be mapped then they may be configured correctly and so cannot be tested in this manner.

Sorry I guess I should have given more context. I used these URLs as an example because even on my own APIs I always get this error using the tool and others such as clairvoyance... I guess maybe I'm missing something here or if the tool is really only effective if you literally already have the entire map...

> WARNING | Error posting to https://_______ Expecting value: line 1 column 1 (char 0)
